server:
  port: 8083
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Greenhillsliu/greentrees.git
          default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    fetch-registry: true
    register-with-eureka: true